// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoA80sXTyC3-BmU1uJWRXgT5Sj3ZPAQc',
    appId: '1:353924248823:web:839b636df23c932c7dcff2',
    messagingSenderId: '353924248823',
    projectId: 'horizon-test-d997a',
    authDomain: 'horizon-test-d997a.firebaseapp.com',
    storageBucket: 'horizon-test-d997a.firebasestorage.app',
    measurementId: 'G-WL4VVYEQFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-HfpQg_Fkf149sn86kEayK89Gm_LItnc',
    appId: '1:353924248823:android:afdd19ee59618f7a7dcff2',
    messagingSenderId: '353924248823',
    projectId: 'horizon-test-d997a',
    storageBucket: 'horizon-test-d997a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAELckk7f7-zlIsJxpc9fwCRyFMXx0w4-E',
    appId: '1:353924248823:ios:338b780c47ee4d6f7dcff2',
    messagingSenderId: '353924248823',
    projectId: 'horizon-test-d997a',
    storageBucket: 'horizon-test-d997a.firebasestorage.app',
    iosBundleId: 'com.example.horizon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAELckk7f7-zlIsJxpc9fwCRyFMXx0w4-E',
    appId: '1:353924248823:ios:338b780c47ee4d6f7dcff2',
    messagingSenderId: '353924248823',
    projectId: 'horizon-test-d997a',
    storageBucket: 'horizon-test-d997a.firebasestorage.app',
    iosBundleId: 'com.example.horizon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoA80sXTyC3-BmU1uJWRXgT5Sj3ZPAQc',
    appId: '1:353924248823:web:952f6e76a0c96b0e7dcff2',
    messagingSenderId: '353924248823',
    projectId: 'horizon-test-d997a',
    authDomain: 'horizon-test-d997a.firebaseapp.com',
    storageBucket: 'horizon-test-d997a.firebasestorage.app',
    measurementId: 'G-W3HDPKTC54',
  );
}
